git:
  paging:

    ## This line will use customized word-diff unconditionally
    #externalDiffCommand: "~/.word-diff.sh"
    ## Starting from lazygit 0.55.0, this setting honors git's external diff configurations
    useExternalDiffGitConfig: true

  merging:
    ## extra args passed to `git merge`, e.g. --no-ff
    #args: "--no-ff"
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"

customCommands:
  # Support this in the lazygit way: 'read -p "YYYY.mm.dd? " when; git commit --amend --no-edit --date ${when}T12:34:56'
  - key: D
    context: commits
    description: "Change a commit to another date"
    command: 'git commit --amend --no-edit --date {{.Form.when}}T12:34:56'
    output: log
    prompts:
      - type: input
        title: 'Change the commit date to (YYYY.mm.dd)?'
        key: when

  - key: B
    context: files
    description: "Blame the hovered file"
    command: 'git blame {{.SelectedFile.Name | quote}}'
    output: log
